version: '3.7'

services:
  server:
    build: server
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - TMS_URL=tms
      - TMS_PORT=3001
      - REDIS_URL=redis://cache
    restart: unless-stopped
    depends_on: 
      - redis

  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--bind", "redis", "--port", "6379", "--appendonly", "yes"]
    volumes:
      - ../data/redis:/data

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - server

